@startuml "Strahls Klassensdiagramm"
package DTOs {
    
}

package Abstractions {
    interface BackendFactory {

    }
    interface BackendProvider {
        + GetSceneGraph(): ISceneGraph
        + GetRenderer(): IRenderer
    }
    note "Concrete scene graph representation\nis an implementation detail" as n1
    BackendProvider .. n1
    
}

@enduml