@startuml "Strahls Komponentdiagramm"

package Abstractions {
    note "All interfaces in this package are type-erased" as N1
    struct Material {

    }
    ' Object algebra? (so it can be extended by front-end to enable)
    interface Scene {
        + CreateSphere(center, r)
        + CreatePlane()
        + CreateMesh()
        + CreateLightSource()
        + AddPrimitive()
    }
    ' Synchronization
    interface RTPipeline {
        + RenderScene(Scene)
    }
    interface Backend {
        + GetScene()
        + CreateRTPipeline(RTPipelineCreateInfo)
    }
    class RTPipelineCreateInfo {
                
    }
}

' Abstractions -[hidden] Layer

package Layer {
    enum Backends {
        Vulkan
        CPU
        WGPU
    }

    class BackendProvider {
        + CreateBackend(backend: Backends): Abstractions.Backend
    }
}

@enduml