/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Hello {
  x: number
  path: string
  constructor(x: number)
  aaa(): void
}

export declare function plus100(input: number): Hello
