/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CpuSwapchain {
  width: number
  height: number
  channels: number
  constructor()
  acquireNextTexture(): Uint8Array
}

export declare class StrahlState {
  fillFramebuffer(): Promise<void>

}

export declare function wgpuInit(): Promise<StrahlState>
