/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CpuSwapchain {
  width: number
  height: number
  channels: number
  constructor()
  acquireNextTexture(): Uint8Array
}

export declare class Hello {
  x: number
  path: string
  constructor(x: number)
  aaa(): void
}

export declare class StrahlState {

}

export declare function newTexWrapper(): CpuSwapchain

export declare function plus100(input: number): Hello

export declare function wgpuInit(): Promise<StrahlState>
