/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Body {

}

export declare class Geometry {

}

export declare class Material {

}

export declare class Scene {
  addBody(material: Material, geometry: Geometry, info: BodyCreateInfo): void
}

export declare class Strahl {
  constructor(info: StrahlCreateInfo)
  loadMaterial(path: string): Material
  loadModel(path: string): Geometry
}

export interface BodyCreateInfo {
  position: ArrayBuffer
}

export declare const enum StrahlBackend {
  Rasterize = 0
}

export interface StrahlCreateInfo {
  backend: StrahlBackend
}
