/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Anything that can be rendered */
export declare class Body {
  set material(m: Material)
  get material(): Material
  /** Gets the position of the body relative to the world origin. Returns the array of length 3. */
  get position(): Float32Array
  /** Sets the position of the body relative to the world origin. Expects an array of length 3. */
  set position(pos: Float32Array)
}

/**
 * Class wrapping a geometry. So far it doesn't have any methods exposed,
 * so it may thought of as a kind of opaque handler.
 *
 * Geometry in `strahl` is a generic shape that may be used by bodies or light sources.
 */
export declare class Geometry {
  /** Tries to downcast self to the sphere */
  asSphere(): Sphere
  /** Tries to downcast self to the mesh */
  asMesh(): Mesh
}

/** Class representing a light source */
export declare class LightSource {

}

/**
 * Class wrapping a material. So far it doesn't have any methods exposed,
 * so it may thought of as a kind of opaque handler.
 */
export declare class Material {

}

/** Represents geometry of a mesh of triangles */
export declare class Mesh {

}

/** Represents geometry of a single point */
export declare class Point {

}

/**
 * A collection of objects (bodies and lights) that participate in rendering.
 *
 * So far it doesn't have any methods exposed,
 * so it may thought of as a kind of opaque handler.
 */
export declare class Scene {
  /** Adds a body to the scene */
  addBody(info: BodyCreateInfo, material: Material, geometry: Geometry): Body
  /** Adds a light source to the scene */
  addLightSource(info: LightCreateInfo, geometry: Geometry): LightSource
}

/** Represents geometry of a perfect sphere */
export declare class Sphere {

}

/**
 * The entry point to the `strahl`'s API.
 * This class provides methods for creating scenes, managing resources and rendering.
 */
export declare class Strahl {
  /** Creates a new instance of `Strahl` */
  static create(info: StrahlCreateInfo): Promise<Strahl>
  /** Creates an empty scene */
  createScene(): Promise<Scene>
  /** Loads material from given path */
  loadMaterial(path: string): Promise<Material>
  /** Loads model geometry from given path */
  loadModel(path: string): Promise<Geometry>
  /** Loads glTF mesh from file */
  loadMesh(path: string): Promise<Geometry>
  createPointGeometry(): Geometry
  /**
   * Renders the `scene` from `camera`'s point of view
   * Returns a memory-mapped region containing RGBA texture.
   */
  render(scene: Scene, cam: Camera): Promise<Uint8Array>
  /** Creates an instance of `Strahl` with default settings */
  static default(): Promise<Strahl>
}

/** Object aggregating information required to create a [`Body`] */
export interface BodyCreateInfo {
  /**
   * Array of length 3 representing the position of the body
   * relative to the world origin,
   * i.e. the translation applied to the geometry.
   */
  position: ArrayBuffer
  /**
   * Rotation applied to the geometry in its local coordinates,
   * represented as Euler's angles.
   */
  rotation: ArrayBuffer
}

export interface Camera {
  /** The projection. */
  projection: Projection
  /** The pointer being observed by the camera (array of length 3). */
  lookAt: Float32Array
  /** The location of the camera (array of length 3) */
  location: Float32Array
}

/**
 * Object aggregating the information required to create [`LightSource`].
 * The only supported light type so far is omnidirectional: each point
 * of the source's surface emits equal amount of radiance in all direction.
 */
export type LightCreateInfo =
  | {
    type: 'Omnidirectional',
    /** Radiance of the light source in red, green and blue wavelength of spectrum. */
    color: Float32Array,
    /**
   * Array of length 3 representing the position of the light source
   * relative to the world origin,
   * i.e. the translation applied to the geometry.
   */
    position: Float32Array
  }

/**
 * Projection used by the camera. Two types of projection are supported:
 * * orthographic (https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glOrtho.xml),
 * * perspective (https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/gluPerspective.xml)
 */
export type Projection =
  | {
    type: 'Ortho',
    /** Left clipping plane */
    left: number,
    /** Right clipping plane */
    right: number,
    /** Bottom clipping plane */
    bottom: number,
    /** Top clipping plane */
    top: number,
    /** Nearer clipping plane */
    near: number,
    /** Farther clipping plane */
    far: number
  }
  | {
    type: 'Perspective',
    /** Field of view angle in vertical plane, **unit is unspecified so far** */
    fovy: number,
    /** Aspect ratio, i.e. the ration of viewport width to its height */
    aspect: number,
    /** Nearer clipping plane */
    zNear: number,
    /** Farther clipping plane */
    zFar: number
  }

/** The graphics backend implementation used by strahl */
export declare const enum StrahlBackend {
  Rasterize = 0
}

/**
 * Object aggregating the information required to create `Strahl`.
 * New fields (and will) be added in future.
 */
export interface StrahlCreateInfo {
  /** Specifies the rendering backend */
  backend: StrahlBackend
  /** Specifies the width of the viewport (in pixels) */
  width: number
  /** Specified the height of the viewport */
  height: number
}
